# Generated by Django 2.1.3 on 2018-11-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
    ]
